stages:
  - build
  - deploy
build_job:
  stage: build
  tags:
    - website
  script:
    - pwd
    - hugo
    - ls
  artifacts:
    paths:
      - public/
deploy_job:
  stage: deploy
  tags:
    - website
  dependencies:
    - build_job
  script:
    - rm -r /var/www/html/lab2cnew/*
    - mv public/* /var/www/html/lab2cnew/
