stages:
  - build
  - deploy

build_job:
  stage: build
  tags:
    - website
  script:
    - hugo

deploy_job:
  stage: deploy
  tags:
    - website
  script:
    - mv public/* /var/www/html/lab2cnew/
