stages:
  - build
  - deploy
build_job:
  stage: build
  tags:
    - website
  script:
    - hugo
  artifacts:
    paths:
      - public
deploy_job:
  stage: deploy
  tags:
    - website
  dependencies:
    - build_job
  script:
    - rm -rf /var/www/html/lab2cnew/*
    - mv public/* /var/www/html/lab2cnew/
