version: '3.1'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/www/html:/var/www/html
      - /etc/gitlab-runner/gitlab-docker-runner:/etc/gitlab-runner
    network_mode: "bridge"

